### ISSUE TITLE
Prettier: Breeze and Svelte

### ISSUE THREAD

**Issue by edjw** [senkulabs/breeze-lite#11]
If it is a project goal to be adopted by official Breeze, then it might be good to follow their code formatting preferences so the code formatting is at least similar. I think the only thing missing from the new one added to this project is the plugins.

This is [official Breeze's `.prettierrc`](https://github.com/laravel/breeze/blob/2.x/stubs/inertia-common/.prettierrc)

```json
{
    "singleQuote": true,
    "plugins": [
        "prettier-plugin-organize-imports",
        "prettier-plugin-tailwindcss"
    ]
}
```

New Svelte projects from [Svelte's new `sv` CLI](https://github.com/sveltejs/cli) come with this `.prettierrc`. The plugins and overrides would probably make sense for any project with .svelte files.

```json
{
	"useTabs": true,
	"singleQuote": true,
	"trailingComma": "none",
	"printWidth": 100,
	"plugins": [
		"prettier-plugin-svelte"
	],
	"overrides": [
		{
			"files": "*.svelte",
			"options": {
				"parser": "svelte"
			}
		}
	]
}
```

This is the Svelte `.prettierignore` file

```
# Package Managers
package-lock.json
pnpm-lock.yaml
yarn.lock
```

**Comment by kresnasatya** [comment]
Thanks a lot Ed. This is exactly what I wish for this project goal. I will do that around weekend or when I have a spare time on weekdays.

**Comment by kresnasatya** [comment]
Hi Ed, I will close this issue because I have shipped the new Breeze Lite version. Feel free to open the new issue for another discussion. Thanks a lot.
