### ISSUE TITLE
When deleting an account, the modal is still displayed.

### ISSUE THREAD

**Issue by csoutham** [senkulabs/breeze-lite#17]
When deleting a user account, using the "Delete Account" button:

- the action completes, with the data deleted
- the user is logged out and returned to the homepage
- **but** the modal remains, with no way to close of dismiss it

Expectation:
- the modal closes, and the user is shown the homepage

**Comment by kresnasatya** [comment]
Ops, I forget to check this one. I will try this at night. Thanks for the info.

**Comment by kresnasatya** [comment]
Hi Chris, I fixed the issue. Feel free to check and comment here although I close this issue. I wish everything runs well. Thanks a lot.
