### ISSUE TITLE
Investigation

### ISSUE THREAD

**Issue by kresnasatya** [senkulabs/breeze-lite#2]
Command `tsc && vite build` will throw error for Svelte TS.

**Comment by kresnasatya** [comment]
Error in using TS template with Inertia version 2.0.0-beta.2

**Comment by kresnasatya** [comment]
Error when run `tsc && vite build` in svelte + ts template in inertia version 2

**Comment by kresnasatya** [comment]
It's a Inertia package problem. Submitted in: https://github.com/inertiajs/inertia/issues/2075

**Comment by edjw** [comment]
I think it was because of not checking for the existence of `el` in `app.ts`

**Comment by kresnasatya** [comment]
Hi Ed, sorry for late reply. You're right. But, if we add a checker into the `app.ts` file then the code program will be increased a bit. If we check in Laravel Breeze (Inertia Vue & React) it doesn't add any check of `el`.

Inertia + Vue TS: https://github.com/laravel/breeze/blob/a6d02b0ad5a03e7ab12546bf978be33e5c77f806/stubs/inertia-vue-ts/resources/js/app.ts#L19

Inertia + React TS: https://github.com/laravel/breeze/blob/a6d02b0ad5a03e7ab12546bf978be33e5c77f806/stubs/inertia-react-ts/resources/js/app.tsx#L18

My intuition towards on the Inertia Svelte package itself in this code: https://github.com/inertiajs/inertia/blob/9106d74495130a3d82d00daec43c4042b81bdb63/packages/svelte/src/createInertiaApp.ts#L14

The author do that because of PR https://github.com/inertiajs/inertia/pull/2037

Anyway, let the `el` checker exist in the `app.ts` in this moment. I will close this issue. Thank you.
