### ISSUE TITLE
Artisan inertia:start-ssr throws error: route is not defined

### ISSUE THREAD

**Issue by kresnasatya** [senkulabs/breeze-lite#4]
In this case, assets have build with `npm run build` in condition: I use TypeScript with Inertia SSR. Then, run `artisan serve` and `artisan inertia:start-ssr` in separate tabs terminal. Open the `localhost:8000`. Everything works well. But, I see there's an error message from inertia side: `ReferenceError: route is not defined`. Need to figure out because I'm not familiar with inertia SSR.

<img width="1433" alt="Screenshot 2024-11-05 at 06 21 24" src="https://github.com/user-attachments/assets/d15990df-4142-4193-921d-d635f183120f">

**Comment by kresnasatya** [comment]
Setup when at home:

```
// ssr.ts | ssr.js
import { route } from '../../vendor/tightenco/ziggy';
// Reason: later on but this is work!
```

**Comment by saml-dev** [comment]
this was fixed by #7 for typescript. still not working for javascript version so we can probably keep this issue open to fix the js side

**Comment by kresnasatya** [comment]
I have use your PR and now I get a different error message when I build the assets with `npm run build`:

```bash
error during build:
[vite]: Rollup failed to resolve import "ziggy-js" from "/Users/kresnasatya/Projects/svelte-laravel/resources/js/ssr.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

Then, I try to set it on vite.config.js

```js
plugins: [
 // redacted because the same settings
],
build: {
        rollupOptions: {
            external: [
                'ziggy-js'
            ]
        }
    }
```

I run `npm run build` and now assets successfully build. Now, it come to another problem in `php artisan inertia:start-ssr`.

```bash
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ziggy-js' imported from /Users/kresnasatya/Projects/svelte-laravel/bootstrap/ssr/ssr.js
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:916:9)
    at moduleResolve (node:internal/modules/esm/resolve:973:20)
    at defaultResolve (node:internal/modules/esm/resolve:1206:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:404:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:373:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:250:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.20.4
```

It seems that Node fails to figure out where's the 'ziggy-js' package location. I think we need to tell it explicitly as I see in ssr.tsx in Inertia + React: https://github.com/laravel/breeze/blob/a6d02b0ad5a03e7ab12546bf978be33e5c77f806/stubs/inertia-react-ts/resources/js/ssr.tsx#L6 and ssr.ts in Inertia + Vue: https://github.com/laravel/breeze/blob/a6d02b0ad5a03e7ab12546bf978be33e5c77f806/stubs/inertia-vue-ts/resources/js/ssr.ts#L6

Now, ssr.ts in Inertia + Svelte will be like this:

```diff
// ... Same as above
- import { route } from 'ziggy-js';
+ import { route } from '../../vendor/tightenco/ziggy';

// ... Same as below
```

I test again the `inertia:start-ssr` and everything works properly.

<img width="1508" alt="Screenshot 2024-11-09 at 08 54 52" src="https://github.com/user-attachments/assets/4d15c273-4c60-4e3c-b111-3378b47e8456">

**Comment by kresnasatya** [comment]
I close this issue because I don't get the error from inertia:start-ssr after update the ssr file.
